services:
  app:
    build: .
    container_name: spring-boot-mailing-system
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/spring_db
      SPRING_DATASOURCE_USERNAME: spring_user
      SPRING_DATASOURCE_PASSWORD: spring123
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: spring-boot-mailing-system-db
    environment:
      POSTGRES_DB: spring_db
      POSTGRES_USER: spring_user
      POSTGRES_PASSWORD: spring123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: