name: CI (Maven tests + Docker image)

on:
  push:
    branches: ["**"]
  pull_request:

# Cancel older runs for the same branch/PR to save minutes
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    env:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true
      # Testcontainers uses Docker on the runner; no extra services are required.

    steps:
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run unit & integration tests (with Testcontainers)
        run: mvn -B -e -DskipITs=false -Dtest='*' test

      - name: Package app (skip tests)
        run: mvn -B -e -DskipTests package

      - name: Upload test reports (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-and-failsafe-reports
          path: |
            **/target/surefire-reports/**
            **/target/failsafe-reports/**
          if-no-files-found: ignore

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (local)
        run: docker build --pull --tag myapp:latest .

      - name: Show images
        run: docker images | head -n 10